<a href="https://colab.research.google.com/github/Deepansh-tandon/cognitive-assignments/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
a=np.array([1,2,3,4,5]);
print(a)
print(a+2)
print(a*3)
print(a/2)

[1 2 3 4 5]
[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [11]:
a = a[ : :-1]
a

array([5, 4, 3, 2, 1])

In [15]:
def freqele(arr):
    unique_v,count=np.unique(arr,return_counts=True)
    max=np.argmax(count)
    freq=unique_v[max]
    i=np.where(arr==freq)
    return freq,i[0]

x1=np.array([1,2,3,4,5,1,2,1,1,1])
y1=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

a1,a2=freqele(x1)
b1,b2=freqele(y1)

print(a1,a2)
print(b1,b2)

1 [0 5 7 8 9]
1 [0 1 2]


In [13]:
y=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(y)
print(y[0][1])
print(y[2][0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
20
70


In [12]:
x=np.array(np.linspace(10,100,25))
print(x)
print(x.shape)
print(x.size)
print(x.dtype)
print(x.itemsize*x.size)
print(x.reshape(5,5))
# not an inbuilt function for transpose print(x.T)
print(x.reshape(5,5).T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)
25
float64
200
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


In [17]:
ucs420_deepansh=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_deepansh)
print(np.mean(ucs420_deepansh))
print(np.median(ucs420_deepansh))
print(np.max(ucs420_deepansh))
print(np.min(ucs420_deepansh))
print(np.unique(ucs420_deepansh))

reshape_ucs420_deepansh=np.reshape(ucs420_deepansh,(4,3))
print(reshape_ucs420_deepansh)

resize_ucs420_deepansh=np.resize(ucs420_deepansh,(2,3))
print(resize_ucs420_deepansh)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
